version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wordpress-network
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:latest
    container_name: wordpress-container
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 123123
    ports:
      - "8082:80"
    networks:
      - wordpress-network


volumes:
  mysql_data:

networks:
  wordpress-network:
