version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8082:80"  # Port untuk WordPress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: wordpress  # Password untuk WordPress
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress_data:/var/www/html

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress  # Password root MySQL
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: wordpress  # Password untuk pengguna MySQL
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8083:80"  # Port untuk phpMyAdmin
    environment:
      PMA_HOST: db
      PMA_USER: exampleuser
      PMA_PASSWORD: wordpress  # Password untuk pengguna MySQL
    depends_on:
      - db

volumes:
  wordpress_data:
  db_data:
