name: 'deploy-nginx-mysql'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  deploy:
    runs-on: [self-hosted] # Menunjukkan bahwa ini harus berjalan di self-hosted runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy MySQL and nginxkontol
      run: |
        # Pull the latest images
        docker pull mysql:latest
        docker pull nginx:latest

        # Run the MySQL container
        docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} -d mysql:latest

        # Run the Nginx container
        docker run --name nginx-container -p 8080:8080 -v /etc/nginx/conf.d:/etc/nginx/conf.d -d nginx:latest

        # Create an Nginx configuration file
        echo "server {
            listen 80;
            server_name your_domain_or_IP;

            location / {
                proxy_pass http://localhost:80;
                proxy_set_header Host \$host;
                proxy_set_header X-Real-IP \$remote_addr;
                proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto \$scheme;
            }
        }" > /etc/nginx/conf.d/default.conf

        # Reload Nginx to apply the configuration
        docker exec nginx-container nginx -s reload
