name: 'deploy-nginx-mysql'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  deploy:
    runs-on: [self-hosted] # Menunjukkan bahwa ini harus berjalan di self-hosted runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy MySQL and nginxkontol
      run: |
        # Pull the latest images
        docker pull mysql:latest
        docker pull nginx:latest

        # Run the MySQL container
        docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} -d mysql:latest

        # Run the Nginx container
        docker run --name nginx-container -p 80:8080 -v /etc/nginx/conf.d:/etc/nginx/conf.d -d nginx:latest

        # Reload Nginx to apply the configuration
        docker exec nginx-container nginx -s reload
