name: 'deploy-mysql-docker'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  deploy:
    runs-on: [self-hosted] # Menunjukkan bahwa ini harus berjalan di self-hosted runner
    steps:
    - name: Checkout code bosa ga
      uses: actions/checkout@v2

    - name: Deploy to VPS
      run: |
        # Pull the latest MySQL image
        docker pull mysql:latest
        # Run the MySQL container with the specified root password
        docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} -d mysql:latest
