name: 'Deploy to VPS'

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy with Docker Compose
      run: |
        docker-compose down  # Optional: Stop and remove existing containers
        docker-compose up -d
