name: Deploy WordPress Application

on:
  push:
    branches:
      - main  # Ganti dengan nama branch yang Anda gunakan

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      - name: Start services
        run: |
          docker-compose -f docker-compose.yml up -d
